# Production Database Configuration for B2Battle
doctrine:
    dbal:
        # Production database optimizations
        options:
            # MySQL specific optimizations
            1002: 'SET sql_mode="STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"'
        
        # Connection pooling and performance
        connections:
            default:
                # Enable query logging only for errors
                logging: false
                profiling: false
                
                # Connection options for production
                options:
                    # MySQL optimizations
                    !php/const PDO::MYSQL_ATTR_INIT_COMMAND: 'SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci'
                    !php/const PDO::ATTR_TIMEOUT: 30
                    !php/const PDO::ATTR_ERRMODE: !php/const PDO::ERRMODE_EXCEPTION
                    
    orm:
        # Production ORM optimizations
        auto_generate_proxy_classes: false
        enable_lazy_ghost_objects: true
        
        # Query cache for better performance
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
            
        # Metadata cache
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
            
        # Result cache
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

# Cache pools for Doctrine
framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
                
            doctrine.system_cache_pool:
                adapter: cache.system
