# Production Logging Configuration for B2Battle
monolog:
    handlers:
        # Main application log
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
            max_files: 10
            formatter: monolog.formatter.json
            
        # Security log
        security:
            type: rotating_file
            path: '%kernel.logs_dir%/security.log'
            level: info
            max_files: 10
            channels: ['security']
            formatter: monolog.formatter.json
            
        # Payment log
        payment:
            type: rotating_file
            path: '%kernel.logs_dir%/payment.log'
            level: info
            max_files: 30
            channels: ['payment']
            formatter: monolog.formatter.json
            
        # Error log for critical issues
        critical:
            type: rotating_file
            path: '%kernel.logs_dir%/critical.log'
            level: critical
            max_files: 10
            formatter: monolog.formatter.json
            
        # Console errors
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
            
    formatters:
        json:
            class: Monolog\Formatter\JsonFormatter
